### ISSUE TITLE
GetAllInstances<>() does not get instances with specified service names in version 4.0.0

### ISSUE THREAD

**Issue by fremo917** [seesharper/LightInject.Microsoft.DependencyInjection#212]
Hi,

I bumped into some breaking changes while updating to 4.0.0 from 3.7.1.

Example:
```
var container = new ServiceContainer(ContainerOptions.Default.Clone().WithMicrosoftSettings());
container.Register<IExampleScopedService, ExampleScopedService>("Service1");
container.Register<IExampleScopedService, ExampleScopedService>("Service2");
container.Register<IExampleScopedService, ExampleScopedService>();
var result = container.GetAllInstances<IExampleScopedService>();
```

In version 3.7.1 result.Count would be 3 while in version 4.0.0 result.Count is 1. I.e. only those without ServiceName is returned.

Is there a work around in order to get all instances, even those with service names?

Thanks in advance

**Comment by seesharper** [comment]
Yeah, this is actually a breaking change and it is because MS.DI now also has support for named/keyed services and LightInject.Microsoft.DependencyInjection needs to adhere to the specifications in order to be a 100% compatible replacement for MS.DI. 

What you can do here is register all with a service name and resolve it as as follows.

```c#
container.Register<IExampleScopedService, ExampleScopedService>("Service1");
container.Register<IExampleScopedService, ExampleScopedService>("Service2");
container.Register<IExampleScopedService, ExampleScopedService>("Service3");
var result = container.GetInstance<IEnumerable<IExampleScopedService>>("*");
```

> Note "*" just means all of the named services.

Alternatively you can register all services without a service name. I am only going to assume here that you probably have different implementations of `IExampleScopedService`

So it would look like this 

```c#
container.Register<IExampleScopedService, ExampleScopedService>();
container.Register<IExampleScopedService, AnotherExampleScopedService>();
container.Register<IExampleScopedService, YetAnotherExampleScopedService>();
var result = container.GetInstance<IEnumerable<IExampleScopedService>>();
```
Hope this helps

**Comment by fremo917** [comment]
I see. My first reaction was to override GetInstance to always use * but then I had some tests failing because some unnamed services was not found with GetInstance("*").. So I ended up just replacing my one use of GetAllInstances with ("*").

But if I would have wanted to keep the same functionality as before i think I would have to do
```
var result1 = container.GetInstance<IEnumerable<IExampleScopedService>>("*");
var result2 = container.GetAllInstances<IExampleScopedService>();
var result = result1.Concat(result2);
```

Thanks for your help. I am closing the issue.
